"""
This type stub file was generated by pyright.
"""

from typing import Optional, Type, TypeVar
from dacite.config import Config
from dacite.data import Data

T = TypeVar("T")
def from_dict(data_class: Type[T], data: Data, config: Optional[Config] = ...) -> T:
    """Create a data class instance from a dictionary.

    :param data_class: a data class type
    :param data: a dictionary of a input data
    :param config: a configuration of the creation process
    :return: an instance of a data class
    """
    ...

