"""
This type stub file was generated by pyright.
"""

from dataclasses import Field
from typing import Any, List, Type, TypeVar
from dacite.data import Data

T = TypeVar("T", bound=Any)
class DefaultValueNotFoundError(Exception):
    ...


def get_default_value_for_field(field: Field) -> Any:
    ...

def create_instance(data_class: Type[T], init_values: Data, post_init_values: Data) -> T:
    ...

def get_fields(data_class: Type[T]) -> List[Field]:
    ...

