"""
This type stub file was generated by pyright.
"""

import httpcore
from typing import List, Mapping, Optional, Tuple
from .._types import CertTypes, VerifyTypes

class URLLib3Transport(httpcore.SyncHTTPTransport):
    def __init__(self, *, verify: VerifyTypes = ..., cert: CertTypes = ..., trust_env: bool = ..., pool_connections: int = ..., pool_maxsize: int = ..., pool_block: bool = ...) -> None:
        ...
    
    def request(self, method: bytes, url: Tuple[bytes, bytes, Optional[int], bytes], headers: List[Tuple[bytes, bytes]] = ..., stream: httpcore.SyncByteStream = ..., timeout: Mapping[str, Optional[float]] = ...) -> Tuple[bytes, int, bytes, List[Tuple[bytes, bytes]], httpcore.SyncByteStream]:
        ...
    
    def close(self) -> None:
        ...
    


class URLLib3ProxyTransport(URLLib3Transport):
    def __init__(self, *, proxy_url: str, proxy_headers: dict = ..., verify: VerifyTypes = ..., cert: CertTypes = ..., trust_env: bool = ..., pool_connections: int = ..., pool_maxsize: int = ..., pool_block: bool = ...) -> None:
        ...
    


