# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: name

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: pylint-black
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint **/*.py
    - name: Check formatting with black
      run: |
        pip install black
        black --check **/*.py